### PR TITLE
implement AndOrGraphSearch algorithm

### PR DESCRIPTION
**Pull request by BusyByte**
Issue: https://github.com/aimacode/aima-scala/issues/6

### CODE REVIEW

**Comment by BusyByte** [comment]
@a1shadows can I get a review of this PR?

**Comment by a1shadows** [comment]
@BusyByte Yes, of course. Could I do it after the 17th, please? I have a college exam that day.

**Comment by BusyByte** [comment]
@a1shadows sure thing, no hurry

**Comment by a1shadows** [comment]
@BusyByte Hey, you can add me as a reviewer. I'll look over the pull request to the best of my abilities.

**Comment by BusyByte** [comment]
@a1shadows I think @ctjoreilly may have to I don't have admin rights on the repo and your name doesn't come up if I try to request a review.

**Pull request merged**
