### PR TITLE
Game trait created.

### PR DESCRIPTION
**Pull request by a1shadows**
In preparation for #9 .

### CODE REVIEW

**Comment by BusyByte** [comment]
@a1shadows can you link this PR to the GitHub issue it is for?

**Comment by a1shadows** [comment]
This pull request is in preparation for issue #9 . But, it won't close it. So, I didn't reference it. Should I?

**Comment by a1shadows** [comment]
@BusyByte yes, of course.

**Comment by BusyByte** [comment]
@a1shadows let me know if you want me to merge this or if you can do it?  I'm not sure what the permissions are on the repo.

**Comment by a1shadows** [comment]
@BusyByte I can't do it. I don't have write access. Could you do it, please?

**Pull request merged**
